function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 27-Nov-2014 17:04:01

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(1,1,1,'Parent',figure1,...
    'XTickLabel',{'0','2','4','6','8','10','12','14','16','18','20'});
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[0 20]);
box(subplot1,'on');
hold(subplot1,'all');

% Create plot
plot(X1,Y1,'Parent',subplot1,'MarkerFaceColor',[0 0 0],...
    'MarkerEdgeColor',[0 0 0],...
    'MarkerSize',5,...
    'Marker','o');

% Create xlabel
xlabel('distance (m)');

% Create ylabel
ylabel('height (m)');

% Create legend
legend1 = legend(subplot1,'show');
set(legend1,'Visible','off');

